{ config, pkgs, lib, ... }:

let
  admins = (import ./admins.nix).admins;

  # ---- Minecraft settings --------------------------------------------------
  mcVersion = "1.21.9"; # change to upgrade/downgrade the server version
  # Pin the Fabric loader (e.g. "0.16.10") or leave null for the latest.
  fabricLoaderVersion = null;
  serverVersion = "fabric-${lib.replaceStrings [ "." ] [ "_" ] mcVersion}";

  serverPackage = pkgs.fabricServers.${serverVersion}.override (
    lib.optionalAttrs (fabricLoaderVersion != null) { inherit fabricLoaderVersion; }
  );
in
{
  imports = [
    # Generated by `nixos-generate-config`; do not edit, regen if needed.
    ./hardware-configuration.nix
  ];

  # Set this to the NixOS release the server was first installed with.
  system.stateVersion = "24.11";

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "nixos";

  # Enable networking.
  networking.networkmanager.enable = true;

  networking.firewall = {
    allowedTCPPorts = [ 21 22 25565 ];
    allowedUDPPorts = [ 24454 ];
  };

  networking.interfaces.enp2s0.ipv4.addresses = [
    {
      address = "10.34.144.50";
      prefixLength = 24;
    }
  ];
  networking.defaultGateway.address = "10.34.144.1";
  networking.nameservers = [ "8.8.8.8" ];

  # Time zone.
  time.timeZone = "Europe/Copenhagen";

  # Internationalisation.
  i18n.defaultLocale = "en_DK.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "da_DK.UTF-8";
    LC_IDENTIFICATION = "da_DK.UTF-8";
    LC_MEASUREMENT = "da_DK.UTF-8";
    LC_MONETARY = "da_DK.UTF-8";
    LC_NAME = "da_DK.UTF-8";
    LC_NUMERIC = "da_DK.UTF-8";
    LC_PAPER = "da_DK.UTF-8";
    LC_TELEPHONE = "da_DK.UTF-8";
    LC_TIME = "da_DK.UTF-8";
  };

  # Keymap.
  services.xserver.xkb = {
    layout = "dk";
    variant = "winkeys";
  };
  console.keyMap = "dk-latin1";

  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };

  # The Minecraft server jar is marked unfree.
  nixpkgs.config.allowUnfree = true;

  # ---- Admin users (see admins.nix) -----------------------------------------
  # System user/group that actually runs the Minecraft servers. Kept separate
  # from the "minecraft" admin account defined in admins.nix.
  users.users = lib.mkMerge (
    map (admin: {
      ${admin.username} = {
        isNormalUser = true;
        description = "noname";
        extraGroups = [ "networkmanager" "wheel" "minecraft-server" ];
        openssh.authorizedKeys.keys = admin.sshKeys;
      };
    }) admins
    ++ [
      # Any admin can log in as root.
      {
        root.openssh.authorizedKeys.keys = lib.concatLists (map (admin: admin.sshKeys) admins);
      }
      {
        minecraft-server = {
          isSystemUser = true;
          group = "minecraft-server";
          home = "/srv/minecraft";
          createHome = true;
          homeMode = "770";
        };
      }
    ]
  );

  users.groups.minecraft-server = { };

  # Packages installed in the system profile.
  environment.systemPackages = with pkgs; [
    neovim
    wget
    curl
    screen
    git
    jdk21_headless
    kitty
  ];

  # ---- SSH -------------------------------------------------------------------
  services.openssh = {
    enable = true;
    ports = [ 22 ];
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "prohibit-password";
      AllowUsers = null;
      UseDns = true;
    };
  };

  # ---- Minecraft -------------------------------------------------------------
  services.minecraft-servers = {
    enable = true;
    eula = true;
    dataDir = "/srv/minecraft";
    user = "minecraft-server";
    group = "minecraft-server";
    openFirewall = true;

    servers.minecraft = {
      enable = true;
      autoStart = true;
      package = serverPackage;

      jvmOpts = "-Xms2G -Xmx4G";

      serverProperties = {
        motd = "NixOS Minecraft Server";
        server-port = 25565;
        difficulty = "normal";
        gamemode = "survival";
        max-players = 20;
        view-distance = 10;
        white-list = false;
      };

      # Declarative mods. Get the fetchurl for a mod from Modrinth with:
      #   nix run nixpkgs#... (or use https://modrinth.com and fetchurl)
      # symlinks.mods = pkgs.linkFarmFromDrvs "mods" (builtins.attrValues {
      #   FabricApi = pkgs.fetchurl {
      #     url = "https://cdn.modrinth.com/data/...";
      #     sha512 = "...";
      #   };
      # });
    };
  };
}
